apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
commonLabels:
  environment: dev
images:
  - name: k3d-k3d-registry.local:5000/fortune-backend
    newTag: "1.0"
  - name: k3d-k3d-registry.local:5000/fortune-frontend
    newTag: "1.0"