apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -prod
commonAnnotations:
  environment: prod
patches:
- path: backend-replicas-patch.yaml
- path: frontend-replicas-patch.yaml
